### PR TITLE
Revamp custom color formats

### PR DESCRIPTION
**Pull request by crumblingstatue**
- Normal/custom formats can be selected for display/clipboard separately
- Custom formats are selectable from the same list as normal ones
- Dedicated window to overview and manage custom formats

### CODE REVIEW

**Comment by crumblingstatue** [comment]
Here is a video on how the new feature looks
https://user-images.githubusercontent.com/1521976/139601844-5d1ee422-ad8b-4992-b1b6-c9534715d6bd.mp4

**Comment by vv9k** [comment]
This looks awesome, that was my initial plan to move it to a separate window so glad you made the changes. Looked through the code and tested locally and LGTM. Thanks!

**Comment by crumblingstatue** [comment]
Thank you for merging it!
To be honest, I was expecting you to be a bit more critical when reviewing the code, because I tend to write quite messy code, but I guess it can always be cleaned up later

**Comment by vv9k** [comment]
Thanks for the tip, I will try to be more critical in any following PRs. To be honest, I'm not really expierienced as a maintainer so will have to learn along the way.

**Pull request merged**
